image: emscripten/emsdk:latest

stages:
  - deploy

pages:
  stage: deploy
  tags:
    - emcc
  script:
    # Clone the GitHub repository into the deploy directory with token-based authentication
    - git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/swe-web.git deploy
    # Move the SWE-App.html to index.html
    - cp -R public/* deploy/
    - mv deploy/SWE-App.html deploy/index.html
    - cd deploy
    # Configure Git for the deployment
    - git config user.name "GitLab CI"
    - git config user.email "ben.bieler@tum.de"
    # Stage and commit the changes
    - git add .
    - git commit -m "Deploy to GitHub Pages from GitLab"
    # Push the changes to the GitHub repository
    - git push https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/swe-web.git main
  only:
    - main
