image: emscripten/emsdk:latest

stages:
  - deploy

deploy_to_github:
  stage: deploy
  tags:
    - emcc
  script:
    # Clone the GitHub repository into the deploy directory with token-based authentication
    - git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/swe-web.git deploy
    # Move the files from the public folder into the deploy folder
    - cp -R Public/* deploy/
    - mv deploy/SWE-App.html deploy/index.html
    - cd deploy
    # Configure Git for deployment
    - git config user.name "GitLab CI"
    - git config user.email "ben.bieler@tum.de"
    # Stage and check for changes
    - git add .
    - |
      if ! git diff-index --quiet HEAD; then
        git commit -m "Deploy to GitHub Pages from GitLab"
        git push https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/swe-web.git main
      else
        echo "No changes to commit"
      fi
  only:
    - main
