include(FetchContent)

FetchContent_Declare(
  bgfx
  GIT_REPOSITORY https://github.com/bkaradzic/bgfx.cmake.git
  GIT_TAG        v1.128.8832-488
)

set(BGFX_INSTALL OFF CACHE BOOL "")

set(BX_AMALGAMATED ON CACHE BOOL "")
set(BGFX_AMALGAMATED ON CACHE BOOL "")

set(BGFX_BUILD_TOOLS OFF CACHE BOOL "")
set(BGFX_BUILD_EXAMPLES OFF CACHE BOOL "")
set(BGFX_BUILD_EXAMPLE_COMMON OFF CACHE BOOL "")

set(BGFX_CUSTOM_TARGETS OFF CACHE BOOL "")

set(BGFX_OPENGL_VERSION 40 CACHE STRING "")
set(BGFX_OPENGLES_VERSION 30 CACHE STRING "")

# set(BGFX_CONFIG_RENDERER_WEBGPU OFF CACHE BOOL "")

# set(BGFX_CONFIG_RENDERER_OPENGL ON)
# set(BGFX_CONFIG_RENDERER_OPENGLES OFF)

# set(BX_CONFIG_DEBUG ON)

set(BGFX_WITH_WAYLAND OFF CACHE BOOL "")

if(EMSCRIPTEN)
  set(BGFX_CONFIG_MULTITHREADED OFF)
endif()

if(${CMAKE_BUILD_TYPE} MATCHES Debug)
  set(BGFX_CONFIG_DEBUG_ANNOTATION ON CACHE BOOL "" FORCE)
  set(BX_CONFIG_DEBUG ON CACHE BOOL "" FORCE)
else()
  set(BGFX_CONFIG_DEBUG_ANNOTATION OFF CACHE BOOL "" FORCE)
  set(BX_CONFIG_DEBUG OFF CACHE BOOL "" FORCE)
endif()

set(CMAKE_POLICY_DEFAULT_CMP0077 NEW CACHE STRING "")

FetchContent_MakeAvailable(bgfx)
